# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\Python\qt-badges\designs\add_template.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxMainInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxMainInfo.setEnabled(False)
        self.groupBoxMainInfo.setTitle("")
        self.groupBoxMainInfo.setObjectName("groupBoxMainInfo")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxMainInfo)
        self.formLayout.setObjectName("formLayout")
        self.labelName = QtWidgets.QLabel(self.groupBoxMainInfo)
        self.labelName.setObjectName("labelName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelName)
        self.editName = QtWidgets.QLineEdit(self.groupBoxMainInfo)
        self.editName.setObjectName("editName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editName)
        self.buttonSave = QtWidgets.QPushButton(self.groupBoxMainInfo)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/use.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSave.setIcon(icon1)
        self.buttonSave.setObjectName("buttonSave")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.buttonSave)
        self.gridLayout.addWidget(self.groupBoxMainInfo, 1, 0, 1, 2)
        self.buttonAddBg = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/img-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAddBg.setIcon(icon2)
        self.buttonAddBg.setObjectName("buttonAddBg")
        self.gridLayout.addWidget(self.buttonAddBg, 0, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Шаблон"))
        self.labelName.setText(_translate("MainWindow", "Название"))
        self.buttonSave.setText(_translate("MainWindow", "Сохранить шаблон"))
        self.buttonAddBg.setText(_translate("MainWindow", "Добавить фон"))
