# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\Python\qt-badges\designs\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 539)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addTemplate = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.addTemplate.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/add-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addTemplate.setIcon(icon1)
        self.addTemplate.setObjectName("addTemplate")
        self.horizontalLayout.addWidget(self.addTemplate)
        self.deleteTemplate = QtWidgets.QPushButton(self.centralwidget)
        self.deleteTemplate.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/delete-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteTemplate.setIcon(icon2)
        self.deleteTemplate.setObjectName("deleteTemplate")
        self.horizontalLayout.addWidget(self.deleteTemplate)
        self.editTemplate = QtWidgets.QPushButton(self.centralwidget)
        self.editTemplate.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/edit-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editTemplate.setIcon(icon3)
        self.editTemplate.setObjectName("editTemplate")
        self.horizontalLayout.addWidget(self.editTemplate)
        self.useTemplate = QtWidgets.QPushButton(self.centralwidget)
        self.useTemplate.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/use.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.useTemplate.setIcon(icon4)
        self.useTemplate.setObjectName("useTemplate")
        self.horizontalLayout.addWidget(self.useTemplate)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableTemplates = QtWidgets.QTableView(self.centralwidget)
        self.tableTemplates.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableTemplates.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableTemplates.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableTemplates.setObjectName("tableTemplates")
        self.tableTemplates.horizontalHeader().setStretchLastSection(True)
        self.tableTemplates.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableTemplates)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генератор дипломов"))
        self.addTemplate.setText(_translate("MainWindow", "Добавить шаблон"))
        self.deleteTemplate.setText(_translate("MainWindow", "Удалить шаблон"))
        self.editTemplate.setText(_translate("MainWindow", "Изменить шаблон"))
        self.useTemplate.setText(_translate("MainWindow", "Использовать шаблон"))
